// Package sessions discovers and inspects Claude Code session files stored
// under a profile's config directory.
//
// # Storage layout
//
// Claude Code stores one JSONL file per session at:
//
//	<configDir>/projects/<encoded-cwd>/<uuid>.jsonl
//
// The <encoded-cwd> directory name is the session's working directory with
// path separators replaced by dashes (e.g. "/Users/matt/git/myapp" becomes
// "-Users-matt-git-myapp"). Each line in the JSONL file is a JSON object
// representing one event in the session.
//
// # Record types we care about
//
//   - "type":"user" — the first user message contains the session's working
//     directory (cwd), git branch, and the initial prompt text. We extract
//     these to populate Session.Cwd, Session.GitBranch, and Session.FirstPrompt.
//
//   - "type":"assistant" — assistant messages carry a "slug" field, which is
//     Claude's auto-generated pretty name for the session (e.g.
//     "async-wishing-forest"). We extract the first slug we find into
//     Session.Slug.
//
// # Performance
//
// Session files can be very large (megabytes of tool results and responses).
// All parsing reads line-by-line and exits as soon as both the first user
// record and the first slug are found, so only a small prefix of each file
// is ever read.
package sessions

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Session holds metadata extracted from a Claude Code session JSONL file.
// This is the primary data structure returned by FindByPrefix and consumed
// by the CLI's session listing and resume-validation features.
type Session struct {
	// ID is the session UUID derived from the JSONL filename (without the
	// .jsonl extension). This is the value users pass to --resume.
	ID string

	// Slug is the human-readable session name auto-generated by Claude
	// (e.g. "async-wishing-forest"). It appears on assistant message records
	// in the JSONL, not on user messages. Empty if the session has no
	// assistant responses yet (e.g. a session that was started but never
	// got a reply).
	Slug string

	// Cwd is the absolute working directory path recorded on the first user
	// message. This is the directory the user was in when they started the
	// session, and is used by the --resume cwd safety check to verify the
	// user is in the right directory before resuming.
	Cwd string

	// GitBranch is the git branch name recorded on the first user message.
	// May be empty if the session was started outside a git repository.
	GitBranch string

	// FirstPrompt is the first line of the user's initial message, truncated
	// to 100 characters. Used as a human-readable label to help identify
	// sessions in listings. The content can be a plain string or extracted
	// from the first text block in a content-block array.
	FirstPrompt string

	// ModTime is the JSONL file's last modification time from the filesystem.
	// Used for sorting (newest first) and for the --since time filter.
	ModTime time.Time

	// Path is the absolute filesystem path to the .jsonl file. Retained for
	// debugging and potential future use (e.g. opening the file for deeper
	// inspection).
	Path string
}

// FindByPrefix searches all project directories under configDir for session
// files whose UUID starts with the given prefix. An empty prefix matches all
// sessions.
//
// The search pattern is:
//
//	<configDir>/projects/*/<prefix>*.jsonl
//
// This means it searches across ALL project directories (i.e. all repos),
// not just the current one. Each matching file is parsed to extract session
// metadata.
//
// Results are sorted by ModTime descending (newest first). Files that cannot
// be opened or parsed are silently skipped — a single corrupt session file
// should not prevent listing the rest.
func FindByPrefix(configDir, prefix string) ([]Session, error) {
	projectsDir := filepath.Join(configDir, "projects")
	pattern := filepath.Join(projectsDir, "*", prefix+"*.jsonl")

	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}

	var sessions []Session
	for _, path := range matches {
		s, err := parseSessionMeta(path)
		if err != nil {
			// Skip unreadable or malformed files rather than failing the
			// entire listing. This is intentional — a single corrupt session
			// should not break the sessions command.
			continue
		}
		sessions = append(sessions, s)
	}

	// Sort newest first so the most relevant sessions appear at the top
	// of each repo group in the output.
	sort.Slice(sessions, func(i, j int) bool {
		return sessions[i].ModTime.After(sessions[j].ModTime)
	})
	return sessions, nil
}

// jsonlRecord is the minimal JSON structure we unmarshal from each line in
// the session JSONL. We only need a few fields from what are often very
// large JSON objects (assistant messages can contain entire file contents
// in tool results).
//
// Field mapping:
//   - Type: the record type ("user", "assistant", "permission-mode", etc.)
//   - Cwd: working directory, present on user messages
//   - GitBranch: git branch name, present on user messages
//   - Slug: session pretty name, present on assistant messages
//   - Message: the message content wrapper, present on user messages
type jsonlRecord struct {
	Type      string      `json:"type"`
	Cwd       string      `json:"cwd"`
	GitBranch string      `json:"gitBranch"`
	Slug      string      `json:"slug"`
	Message   userMessage `json:"message"`
}

// userMessage wraps the message content from a user record. The Content
// field is kept as json.RawMessage because it can be either a plain string
// or an array of content blocks (e.g. [{type:"text", text:"..."}, ...]),
// and we need to try both unmarshaling strategies in extractPromptText.
type userMessage struct {
	Content json.RawMessage `json:"content"`
}

// parseSessionMeta reads a session JSONL file and extracts metadata by
// scanning for two things:
//
//  1. The first "type":"user" record — provides cwd, gitBranch, and the
//     first prompt text.
//  2. The first record with a non-empty "slug" field — provides the
//     session's pretty name (appears on assistant messages).
//
// The function reads line-by-line and stops as soon as both are found.
// For a typical session, this means reading only the first 2-4 lines
// out of potentially thousands. The scanner buffer is sized to handle
// very long lines (up to 1MB) that can occur with tool result records.
//
// If the file has no user record (e.g. a session that was created but
// the user never sent a message), the returned Session will have empty
// Cwd, GitBranch, and FirstPrompt fields but will still have a valid
// ID, ModTime, and Path.
func parseSessionMeta(path string) (Session, error) {
	f, err := os.Open(path)
	if err != nil {
		return Session{}, err
	}
	defer func() { _ = f.Close() }()

	info, err := f.Stat()
	if err != nil {
		return Session{}, err
	}

	// Derive the session ID from the filename: "abc123-...-def456.jsonl" → "abc123-...-def456"
	id := strings.TrimSuffix(filepath.Base(path), ".jsonl")
	s := Session{
		ID:      id,
		ModTime: info.ModTime(),
		Path:    path,
	}

	scanner := bufio.NewScanner(f)
	// Session JSONL files can have extremely long lines — a single tool
	// result record may contain an entire file's contents. The default
	// 64KB scanner buffer is often too small, so we allocate up to 1MB.
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	// Track which pieces of metadata we've found so we can stop early.
	foundUser := false
	foundSlug := false

	for scanner.Scan() {
		var rec jsonlRecord
		if err := json.Unmarshal(scanner.Bytes(), &rec); err != nil {
			// Skip lines that aren't valid JSON — could be partial writes
			// or future record formats we don't understand.
			continue
		}

		// Extract cwd, branch, and prompt from the first user message.
		// Later user messages may have different cwd/branch values (if the
		// user changed directories or branches mid-session), but the first
		// one represents where the session was started.
		if !foundUser && rec.Type == "user" {
			s.Cwd = rec.Cwd
			s.GitBranch = rec.GitBranch
			s.FirstPrompt = extractPromptText(rec.Message.Content)
			foundUser = true
		}

		// Extract the slug (pretty name). Claude generates this on the first
		// assistant response, so it appears on assistant records. We grab the
		// first one we see — it's the same across all records in a session.
		if !foundSlug && rec.Slug != "" {
			s.Slug = rec.Slug
			foundSlug = true
		}

		// Once we have both pieces of metadata, no need to read further.
		if foundUser && foundSlug {
			break
		}
	}

	return s, nil
}

// extractPromptText pulls a short text snippet from the message content
// field of a user record.
//
// Claude Code's JSONL stores message content in two formats:
//
//  1. Plain string: {"content": "explain this code"}
//  2. Content block array: {"content": [{"type":"text","text":"explain this code"}]}
//
// This function tries the plain string format first (cheaper to unmarshal),
// then falls back to the array format. In both cases, only the first line
// is returned, truncated to 100 characters, to keep session listings compact.
func extractPromptText(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}

	// Try plain string first — this is the common case for simple prompts.
	var text string
	if err := json.Unmarshal(raw, &text); err == nil {
		return truncate(firstLine(text), 100)
	}

	// Fall back to array of content blocks. This format is used when the
	// message includes images, tool results, or other non-text content
	// alongside the text. We find the first text block and use that.
	var blocks []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	}
	if err := json.Unmarshal(raw, &blocks); err == nil {
		for _, b := range blocks {
			if b.Type == "text" && b.Text != "" {
				return truncate(firstLine(b.Text), 100)
			}
		}
	}

	return ""
}

// firstLine returns the first line of s after trimming leading whitespace.
// Used to extract a single-line summary from potentially multi-line prompts.
func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// truncate shortens s to maxLen characters, appending "..." if truncated.
// Used to keep session prompt labels from blowing out terminal column widths.
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
