// Package statusline manages Claude Code's built-in statusline feature to
// display profile information. Instead of fighting Claude's TUI with PTY
// scroll regions, we leverage the native statusLine setting in settings.json.
//
// The approach:
//  1. Install a small wrapper shell script in the profiles directory.
//  2. The wrapper reads env vars (set by claude-profile at launch) to display
//     profile info, then chains to any pre-existing statusline command.
//  3. Update the profile's settings.json to point at the wrapper.
//
// This gives us a native, non-conflicting status display that coexists with
// Claude's ink-based TUI.
package statusline

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const wrapperFilename = "statusline-wrapper.sh"

// EnvVars that the wrapper script reads at runtime.
const (
	EnvProfileName = "CLAUDE_PROFILE_NAME"
	EnvProfileAuth = "CLAUDE_PROFILE_AUTH"
	EnvProfileSub  = "CLAUDE_PROFILE_SUB"
	EnvOrigCommand = "CLAUDE_PROFILE_ORIG_STATUSLINE"
)

// wrapperScript is the shell script installed into each profile's config dir.
// It outputs profile info as the first line, then chains to any original
// statusline command the user had configured.
const wrapperScript = `#!/bin/bash
# Auto-generated by claude-profile. Do not edit.
# Reads profile info from env vars and chains to original statusline command.
input=$(cat)

# Profile info line (inverse video for visibility)
printf '\033[7m [%s]  Auth: %s  Sub: %s \033[0m' \
  "${CLAUDE_PROFILE_NAME:-unknown}" \
  "${CLAUDE_PROFILE_AUTH:-unknown}" \
  "${CLAUDE_PROFILE_SUB:-unknown}"

# Chain to original statusline command if set
if [ -n "${CLAUDE_PROFILE_ORIG_STATUSLINE}" ]; then
  echo "$input" | eval "${CLAUDE_PROFILE_ORIG_STATUSLINE}"
fi
`

// EnsureWrapper installs the statusline wrapper script into the profile's
// config directory and updates settings.json to use it. Returns the path to
// the wrapper and the original statusline command (if any).
func EnsureWrapper(configDir string) (wrapperPath string, origCmd string, err error) {
	wrapperPath = filepath.Join(configDir, wrapperFilename)

	// Read existing settings.json to find any current statusline command
	origCmd = readOriginalCommand(configDir, wrapperPath)

	// Write the wrapper script
	if err := os.WriteFile(wrapperPath, []byte(wrapperScript), 0700); err != nil {
		return "", "", fmt.Errorf("writing statusline wrapper: %w", err)
	}

	// Update settings.json to point to our wrapper
	if err := updateSettings(configDir, wrapperPath); err != nil {
		return "", "", fmt.Errorf("updating settings.json: %w", err)
	}

	return wrapperPath, origCmd, nil
}

// readOriginalCommand extracts the current statusLine.command from settings.json,
// but only if it's NOT already pointing at our wrapper (to avoid infinite chaining).
func readOriginalCommand(configDir, wrapperPath string) string {
	settingsPath := filepath.Join(configDir, "settings.json")
	data, err := os.ReadFile(settingsPath)
	if err != nil {
		return ""
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		return ""
	}

	sl, ok := settings["statusLine"]
	if !ok {
		return ""
	}

	slMap, ok := sl.(map[string]interface{})
	if !ok {
		return ""
	}

	cmd, ok := slMap["command"].(string)
	if !ok || cmd == "" {
		return ""
	}

	// Don't chain to ourselves
	if cmd == wrapperPath {
		return ""
	}

	return cmd
}

// updateSettings reads settings.json (or creates it), sets the statusLine
// to our wrapper, and writes it back.
func updateSettings(configDir, wrapperPath string) error {
	settingsPath := filepath.Join(configDir, "settings.json")

	var settings map[string]interface{}

	data, err := os.ReadFile(settingsPath)
	if err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			// Corrupted settings — start fresh but preserve the file
			settings = make(map[string]interface{})
		}
	} else {
		settings = make(map[string]interface{})
	}

	settings["statusLine"] = map[string]interface{}{
		"type":    "command",
		"command": wrapperPath,
		"padding": 0,
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling settings: %w", err)
	}

	return os.WriteFile(settingsPath, out, 0644)
}
