name: release-drafter
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  release-drafter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          disable-autolabeler: true
